main: de.splashfish.flinky.Flinky
name: Flinky
load: POSTWORLD
version: 2.17
author: SplashFish
commands:
   flinky:
      description: General commands.
      usage: /flinky <args>
      permission: flinky.general
      permission-message: You don't have <permission>
   fkick:
      description: Flinky-Kick. Will kick anybody, even ops
      usage: /fkick <player>
      permission: flinky.fkick
      permission-message: You don't have <permission>
   fban:
      description: Flinky-Ban. Will ban name and all ips associated with this player
      usage: /fban <player>
      permission: flinky.fban
      permission-message: You don't have <permission>
   funban:
      description: Flinky-unBan. Will unban name and all ips associated with this player
      usage: /funban <player>
      permission: flinky.funban
      permission-message: You don't have <permission>
   ticket:
      description: Flinky-Ticket-System. Players can send Admins a ticket
      usage: /ticket <args>
      permission: flinky.ticket
      permission-message: You don't have <permission>
